routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Frontend Routes
Route::get('/', 'FrontendController@index')->name('index');
Route::get('/flights', 'FrontendController@flights')->name('flights');
Route::get('/hotels', 'FrontendController@hotels')->name('hotels');
Route::get('/blog', 'FrontendController@blog')->name('blog');
Route::get('/about', 'FrontendController@about')->name('about');
Route::get('/contact', 'FrontendController@contact')->name('contact');
Route::get('/blog/{id}', 'FrontendController@blog_single')->name('blog_single');
Route::get('/flight/{id}', 'FrontendController@flight_single')->name('flight_single');
Route::get('/hotel/{id}', 'FrontendController@hotel_single')->name('hotel_single');
Route::get('/tour/{id}', 'FrontendController@tour_single')->name('hotel_single');

//

Auth::routes();
Route::prefix('admin')->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('/flights', 'FlightController')->except('show');
    Route::resource('/hotels', 'HotelController')->except('show');
    Route::resource('/blog', 'BlogController')->except('show');
    Route::resource('/about', 'AboutController')->except(['show', 'store', 'destroy']);
    Route::resource('/gallery', 'GalleryController')->except('show');
    Route::resource('/subs', 'SubscriberController')->except([
        'show', 'edit', 'update', 'destroy', 'create'
    ]);
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = [
        'body', 'title', 'image'
    ];
}

resources/views/layouts/admin/posts/create.blade.php
@extends('layouts.admin.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Creando Post</div>

                <div class="card-body">
                    @if (session('success'))
                        <div class="alert alert-success">
                            {{ session('success') }}
                        </div>
                    @endif

                    <form action="{{route('blog.store')}}" method="POST"
                        enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label for="image">Imagen</label>
                            <input type="file" name="image" id="image" class="form-control">
			            </div>
                        <div class="form-group">
                            <label for="title">Title</label>
                        <input type="text" name="title" id="title" value="{{ $post->title or old('title') }}" class="form-control" >
                        </div>
                        <div class="form-group">
                            <label for="body">Body</label>
                        <input type="text" name="body" id="body" value="{{ $post->body or old('body') }}" class="form-control">
                        </div>
                        <button type="submit">Enviar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/admin/posts/edit.blade.php
@extends('layouts.admin.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Editando Post</div>

                <div class="card-body">
                    @if (session('success'))
                        <div class="alert alert-success">
                            {{ session('success') }}
                        </div>
                    @endif

                    <form action="{{ route('hotels.update') }}" method="POST"
                        enctype="multipart/form-data">
                        @csrf
			            <input name="_method" type="hidden" value="PUT">
                        <div class="form-group">
                            <label for="image">Imagen</label>
                            <input type="file" name="image" id="image" class="form-control">
			            </div>
                        <div class="form-group">
                            <label for="title">Title</label>
                        <input type="text" name="title" id="title" value="{{ $post->title or old('title') }}" class="form-control" placeholder="{{$post->title}}">
                        </div>
                        <div class="form-group">
                            <label for="body">Body</label>
                        <input type="text" name="body" id="body" value="{{ $post->body or old('body') }}" class="form-control" placeholder="{{$post->body}}">
                        </div>
                        <button type="submit">Enviar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/admin/posts/index.blade.php
@extends('layouts.admin.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Listado de Posts <a href="{{ route('blog.create') }}" class="btn btn-primary">Create</a></div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif
                    @if (session('success'))
                        <div class="alert alert-success">
                            {{ session('success') }}
                        </div>
                    @endif
                    <table class="table table-bordered">
                        <tr>
                            <th>#</th>
                            <th>Imagen</th>
                            <th>Titulo</th>
                            <th>Body</th>
                            <th colspan="2">Acciones</th>
                        </tr>
                        @foreach($posts as $post)
                        <tr>
                            <td>{{ $post->id }}</td>
                            <td><img src="{{ asset('gallery/' . $post->image) }}" alt="{{ $post->image }}" width="150"></td>
                            <td>{{ $post->title }}</td>
                            <td>{{ $post->body }}</td>
                            <td><a href="{{ route('blog.edit', $post->id) }}" class="btn btn-primary">Edit</a></td>
                            <td><a href="{{ route('blog.destroy', $post->id) }}" class="btn btn-danger">Delete</a></td>
                        </tr>
                        @endforeach
                    </table>
                    {{ $posts->links() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection