routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Frontend Routes
Route::get('/', 'FrontendController@index')->name('index');
Route::get('/flights', 'FrontendController@flights')->name('flights');
Route::get('/hotels', 'FrontendController@hotels')->name('hotels');
Route::get('/blog', 'FrontendController@blog')->name('blog');
Route::get('/about', 'FrontendController@about')->name('about');
Route::get('/contact', 'FrontendController@contact')->name('contact');
Route::get('/blog/{id}', 'FrontendController@blog_single')->name('blog_single');
Route::get('/flight/{id}', 'FrontendController@flight_single')->name('flight_single');
Route::get('/hotel/{id}', 'FrontendController@hotel_single')->name('hotel_single');
Route::get('/tour/{id}', 'FrontendController@tour_single')->name('hotel_single');

//

Auth::routes();
Route::prefix('admin')->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('/flights', 'FlightController')->except('show');
    Route::resource('/hotels', 'HotelController')->except('show');
    Route::resource('/blog', 'BlogController')->except('show');
    Route::resource('/about', 'AboutController')->except(['show', 'store', 'destroy']);
    Route::resource('/gallery', 'GalleryController')->except('show');
    Route::resource('/subs', 'SubscriberController')->except([
        'show', 'edit', 'update', 'destroy', 'create'
    ]);
});

app/Gallery.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Gallery extends Model
{
    protected $fillable =[
        'image', 'title', 'body'
    ];
}

app/Http/Controllers/GalleryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Gallery;
use Illuminate\Support\Facades\Storage;

class GalleryController extends Controller
{
     /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct(){
        
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $galleries= Gallery::paginate(15);

        return view('layouts.admin.gallery.index', compact('galleries'));
    }

    /**
     * Show the form for creating a new resource. 
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('layouts.admin.gallery.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {   
        $file_name = "sinimagen.png";
        if($request->file('image')){
            $img = $request->file('image');
            $file_name = $img->getClientOriginalName();
            Storage::disk('gallery')->put(
                $file_name,
                file_get_contents($img->getRealPath())
            );
        }
        $photo = Gallery::create([
            'image' => $file_name, 
            'title' => $request->title, 
            'body' => $request->body
        ]);

        return redirect()->route('gallery.index')->with('success', 'Foto agregada');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $gallery = Gallery::findOrFail($id);
        return view('layouts.admin.gallery.edit', compact('gallery'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {   
        $file_name = "sinimagen.png";
        if($request->file('image')){
            $img = $request->file('image');
            $file_name = $img->getClientOriginalName();
            Storage::disk('gallery')->put(
                $file_name,
                file_get_contents($img->getRealPath())
            );
        }
        $photo = Gallery::findOrFail($id)->update([
            'image' => $file_name, 
            'title' => $request->title, 
            'body' => $request->body
        ]);
        return redirect()->route('gallery.index')->with('success', 'Foto actualizada');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Gallery::destroy($id);
        return redirect()->route('gallery.index')->with('status', 'Foto eliminada');
    }
}

resources/views/layouts/admin/gallery/create.blade.php
@extends('layouts.admin.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Cargando Imagen</div>

                <div class="card-body">
                    @if (session('success'))
                        <div class="alert alert-success">
                            {{ session('success') }}
                        </div>
                    @endif

                    <form action="{{ route('gallery.store') }}" method="POST"
                        enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label for="image">Imagen</label>
                            <input type="file" name="image" id="fileimage" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="title">Titulo</label>
                            <input type="text" name="title" id="title" value="{{ $gallery->title or old('title') }}" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="body">Body</label>
                            <input type="text" name="body" id="body" value="{{ $gallery->body or old('body') }}" class="form-control">
                        </div>                        
                        <button type="submit">Enviar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/admin/gallery/edit.blade.php
@extends('layouts.admin.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Editando Imagen</div>

                <div class="card-body">
                    @if (session('success'))
                        <div class="alert alert-success">
                            {{ session('success') }}
                        </div>
                    @endif

                    <form action="{{ route('gallery.update', $gallery->id) }}" method="POST"
                        enctype="multipart/form-data">
                        @csrf
			        <input name="_method" type="hidden" value="PUT">
                    <div class="form-group">
                        <label for="image">Imagen</label>
                        <input type="file" name="image" id="image" class="form-control">
			        </div>
			        <div class="form-group">
                        <label for="title">Titulo</label>
                        <input type="text" name="title" id="title" value="{{ $gallery->title or old('title') }}" class="form-control" placeholder="{{$gallery->title}}">
			        </div>
			        <div class="form-group">
                        <label for="body">Body</label>
                    <input type="text" name="body" id="body" value="{{ $gallery->body or old('body') }}" class="form-control" placeholder="{{$gallery->body}}">
			        </div>
                        <button type="submit">Enviar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/admin/gallery/index.blade.php
@extends('layouts.admin.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Listado de Imagenes <a href="{{ route('gallery.create') }}" class="btn btn-primary">Create</a></div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif
                    <table class="table table-bordered">
                        <tr>
                            <th>#</th>
                            <th>Imagen</th>
                            <th>Titulo</th>
                            <th>Descripcion</th>
                            <th colspan="2">Acciones</th>
                        </tr>
                        @foreach($galleries as $img)
                        <tr>
                            <td>{{ $img->id }}</td>
                            <td><img src="{{ asset('gallery/' . $img->image) }}" alt="{{ $img->image }}" width="150"></td>
                            <td>{{ $img->title }}</td>
                            <td>{{ $img->body }}</td>
                            <td><a href="{{ route('gallery.edit', $img->id) }}" class="btn btn-primary">Edit</a></td>
                            <td><a href="{{ route('gallery.destroy', $img->id) }}" class="btn btn-danger">Delete</a></td>
                        </tr>
                        @endforeach
                    </table>
                    {{ $galleries->links() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection