routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Frontend Routes
Route::get('/', 'FrontendController@index')->name('index');
Route::get('/flights', 'FrontendController@flights')->name('flights');
Route::get('/hotels', 'FrontendController@hotels')->name('hotels');
Route::get('/blog', 'FrontendController@blog')->name('blog');
Route::get('/about', 'FrontendController@about')->name('about');
Route::get('/contact', 'FrontendController@contact')->name('contact');
Route::get('/blog/{id}', 'FrontendController@blog_single')->name('blog_single');
Route::get('/flight/{id}', 'FrontendController@flight_single')->name('flight_single');
Route::get('/hotel/{id}', 'FrontendController@hotel_single')->name('hotel_single');
Route::get('/tour/{id}', 'FrontendController@tour_single')->name('hotel_single');

//

Auth::routes();
Route::prefix('admin')->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('/flights', 'FlightController')->except('show');
    Route::resource('/hotels', 'HotelController')->except('show');
    Route::resource('/blog', 'BlogController')->except('show');
    Route::resource('/about', 'AboutController')->except(['show', 'store', 'destroy']);
    Route::resource('/gallery', 'GalleryController')->except('show');
    Route::resource('/subs', 'SubscriberController')->except([
        'show', 'edit', 'update', 'destroy', 'create'
    ]);
});

app/About.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class About extends Model
{
    protected $fillable = [
        'history', 'title', 'resume', 'image'
    ];
}

app/Http/Controllers/AboutController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\About;
use Illuminate\Support\Facades\Storage;

class AboutController extends Controller
{
      /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct(){
        
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $about = About::get();
        return view('layouts.admin.about.index', compact('about'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('layouts.admin.about.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $about = About::findOrFail($id);
        return view('layouts.admin.about.edit', compact('about'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        
        $about = About::findOrFail($id)->update([
            'history' => $request->history, 
            'title' => $request->title,
            'resume' =>$request->resume
        ]);

        return redirect()->route()->with('success', 'Acerca de... Actualizado');
    }

}

resources/views/layouts/admin/about/index.blade.php
@extends('layouts.admin.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Listado de Imagenes <a href="{{ route('gallery.create') }}" class="btn btn-primary">Create</a></div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif
                    <table class="table table-bordered">
                        <tr>
                            <th>#</th>
                            <th>Imagen</th>
                            <th>Titulo</th>
                            <th>Descripcion</th>
                            <th colspan="2">Acciones</th>
                        </tr>
                        @foreach($galleries as $img)
                        <tr>
                            <td>{{ $img->id }}</td>
                            <td><img src="{{ asset('gallery/' . $img->image) }}" alt="{{ $img->image }}" width="150"></td>
                            <td>{{ $img->title }}</td>
                            <td>{{ $img->description }}</td>
                            <td><a href="{{ route('gallery.edit', $img->id) }}" class="btn btn-primary">Edit</a></td>
                            <td><a href="{{ route('gallery.destroy', $img->id) }}" class="btn btn-danger">Delete</a></td>
                        </tr>
                        @endforeach
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection